### ISSUE TITLE
Add option to sort by severity

### ISSUE THREAD

**Issue by ArieHein** [jdhitsolutions/MemoryTools#4]
add a -SortBy or similar option to sort the output by severity, so critical or warning come first or separate the list into sections based on the severity

**Comment by jdhitsolutions** [comment]
I'll think about it. Although PowerShell already has tools for sorting or grouping. The paradigm is for cmdlets and functions to do one thing and write objects to the pipeline. If you need to do something else, then pipe to a command that handles that task.

**Comment by jdhitsolutions** [comment]
However, I could see a use case for a parameter to limit output based on Severity so the command might be:

Get-MemoryUsage -computer $c -severity Critical

**Comment by jdhitsolutions** [comment]
This has been addressed in 0.2.5. Waiting to hear how it works before I close this issue.
