### ISSUE TITLE
Replace Write-Host with TMOutput module ?

### ISSUE THREAD

**Issue by it-praktyk** [jdhitsolutions/MemoryTools#6]
Hi,
I think that Write-Host can be replaced by [TMOutput module](https://www.powershellgallery.com/packages/TMOutput/1.1) .

I asked the author what license is for this module.

**Comment by jdhitsolutions** [comment]
As a rule, I'm reluctant to take dependencies on external modules, even my own. What does TMOutput offer that would be an improvement over what I am doing now?
